# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170629_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tp_master_id',
            field=models.IntegerField(null=True),
        ),
    ]
