# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_tp_master_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('about', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='people')),
            ],
        ),
    ]
