# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='guide',
            field=models.ManyToManyField(to='events.Guide'),
        ),
    ]
