# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('review', models.TextField(null=True)),
                ('event', models.ManyToManyField(to='events.Event')),
            ],
        ),
    ]
