# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20170629_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='permalink',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
