# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_permalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='nick',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
