# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_guide_nick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='event',
            field=models.ManyToManyField(blank=True, to='events.Event'),
        ),
    ]
