# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attachment',
            field=models.ManyToManyField(null=True, to='events.Attachment'),
        ),
    ]
