# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20170701_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attachments',
        ),
        migrations.AddField(
            model_name='attachment',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
