# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20170701_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='telegram_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='guides',
            field=models.ManyToManyField(blank=True, to='events.Guide'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tp_master_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
